version: '3'
services:

  video-streaming1:
    image: video-streaming1
    build: 
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
     - "3001:3001"
    environment:
      - PORT=3001
    restart: "no"
  
  video-streaming2:
    image: video-streaming2
    build: 
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
     - "3002:3002"
    environment:
      - PORT=3002
    restart: "no"
  
  video-streaming3:
    image: video-streaming3
    build: 
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
     - "3003:3003"
    environment:
      - PORT=3003
    restart: "no"

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - video-streaming1
      - video-streaming2
      - video-streaming3
